
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // This config's datasource fully overwrites schema.prisma's own
    // datasource block (directUrl included) — setting it here, not there,
    // is what actually routes migrations through Neon's direct/unpooled
    // connection instead of the pooled one, which doesn't reliably support
    // the advisory lock migrations need.
    directUrl: env("DATABASE_URL_UNPOOLED"),
  },
});
